"""Render controlled outage measurements without imposing runner latency gates."""

import argparse
import json
from pathlib import Path


def number(value):
    return "not observed" if value is None else f"{value:.2f}"


def build_page(data):
    if data["schemaVersion"] != 1:
        raise ValueError("Unsupported outage result schema")
    options = data["options"]
    scenarios = data["scenarios"]
    if len(scenarios) != 4:
        raise ValueError("Expected all four compositions")
    lines = [
        "---", "sidebar_label: Outage and recovery", "---", "",
        "<!-- Generated by .github/scripts/outage_docs.py; do not edit measurement rows. -->", "",
        "# Controlled outage and recovery", "",
        "An open-loop load generator exercises Kevlar against an in-process asynchronous dependency. "
        "Each composition gets fresh strategy state and the same healthy, slowdown, outage, and recovery schedule. "
        "These measurements describe the configured simulation, not production capacity or a comparison with another library.", "",
        f"Measured {data['timestamp']} at commit `{data['commit']}`.", "",
        "## Request outcomes and latency", "",
        "Latency starts at the scheduled arrival, including scheduler delay and queue time. "
        "p95/p99 include every submitted outcome, including fast pipeline rejections; success p99 is separate. "
        "Harness rejections remain in offered/failed counts but have no submitted latency. "
        "Requests belong to their scheduled-arrival phase, even when they finish later.", "",
        '<div style={{overflowX: "auto"}}>', "",
        "| Composition | Phase | Offered | Success / failed | p95 / p99 ms | Success p99 ms | Scheduler p99 ms |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for scenario in scenarios:
        if scenario["activeAfterDrain"] != 0:
            raise ValueError("Downstream work did not drain")
        for phase in scenario["phases"]:
            if phase["succeeded"] + phase["failed"] != phase["offered"]:
                raise ValueError("Incomplete request accounting")
            lines.append(f"| {scenario['name']} | {phase['name']} | {phase['offered']} | "
                         f"{phase['succeeded']} / {phase['failed']} | {number(phase['latencyP95Milliseconds'])} / {number(phase['latencyP99Milliseconds'])} | "
                         f"{number(phase['successLatencyP99Milliseconds'])} | {number(phase['schedulerLagP99Milliseconds'])} |")
    lines += ["", "</div>", "", "## Offered load and downstream amplification", "",
              "Submitted means accepted by the harness. Admitted means at least one dependency attempt began. "
              "A request can be admitted and later rejected by the circuit breaker on a retry. "
              "Attempt counts below belong to logical requests in the row; JSON also records attempts by actual start phase.", "",
              '<div style={{overflowX: "auto"}}>', "",
              "| Composition | Phase | Submitted / admitted | Rejected: harness / limiter / circuit | Attempts | Attempts / offered | Attempts / admitted |",
              "|---|---|---:|---:|---:|---:|---:|"]
    for scenario in scenarios:
        for phase in scenario["phases"]:
            lines.append(f"| {scenario['name']} | {phase['name']} | {phase['submitted']} / {phase['admitted']} | "
                         f"{phase['harnessRejected']} / {phase['concurrencyRejected']} / {phase['circuitRejected']} | {phase['downstreamAttempts']} | "
                         f"{phase['attemptsPerOfferedRequest']:.2f} | {phase['attemptsPerAdmittedRequest']:.2f} |")
    lines += ["", "</div>", "", "## Recovery and hedge cleanup", "",
              "Recovery time ends at the later of the end of the first fully successful 250 ms scheduled-arrival window "
              "and completion of every request in that window, measured from the recovery phase boundary. "
              "The window must include at least floor(rate × 0.25), minimum one, successful arrivals. "
              "Any harness shedding or pipeline rejection invalidates that window. Not observed means no qualifying complete window.", "",
              "Cancelled attempts include cancelled hedge losers. Cleanup delay is measured after caller completion, clamped to zero. "
              "Every attempt must finish cleanup before a scenario publishes results or the next scenario starts.", "",
              '<div style={{overflowX: "auto"}}>', "",
              "| Composition | Recovery ms | Cancelled | Losers pending at caller completion | Cleanup p99 / max ms | Peak logical / downstream | Active after drain |",
              "|---|---:|---:|---:|---:|---:|---:|"]
    for scenario in scenarios:
        lines.append(f"| {scenario['name']} | {number(scenario['recoveryMilliseconds'])} | {scenario['cancelledAttempts']} | "
                     f"{scenario['losersPendingAtCallerCompletion']} | {scenario['cleanupAfterCallerP99Milliseconds']:.2f} / "
                     f"{scenario['cleanupAfterCallerMaximumMilliseconds']:.2f} | {scenario['peakLogicalInFlight']} / {scenario['peakDownstreamInFlight']} | 0 |")
    dependency = data["dependency"]
    lines += ["", "</div>", "", "## Configuration and limitations", "",
              f"- {options['requestsPerSecond']} offered requests/s, {options['phaseSeconds']} seconds per phase, "
              f"four phases per composition, and a harness cap of {options['maximumInFlight']} active logical requests.",
              "- Arrivals keep their scheduled times when the runner falls behind; delayed arrivals catch up without waiting for prior responses. "
              "Scheduler lag exposes bursts caused by a saturated generator. High lag or harness shedding limits interpretation.",
              f"- Healthy/recovery dependency latency: {dependency['healthyMilliseconds']} ms. Slowdown: first attempt "
              f"{dependency['slowMilliseconds']} ms, additional attempts {dependency['alternateMilliseconds']} ms. "
              "This intentionally models a slow original replica with a faster alternate; hedging will not help uniformly slow replicas.",
              f"- Outage: every attempt fails after {dependency['failureMilliseconds']} ms. An attempt uses the phase at its start, "
              "so outstanding outage attempts can fail after recovery begins.",
              f"- Cancelled attempts perform {dependency['cleanupMilliseconds']} ms of asynchronous cleanup before completing.",
              "- Retry: two extra attempts with no backoff. Breaker: five consecutive handled failures, "
              f"{dependency['breakMilliseconds']} ms break. Limiter: {dependency['concurrency']} permits, {dependency['queueLimit']} queued. "
              f"Hedge: one extra attempt after {dependency['hedgeMilliseconds']} ms; handled failures can launch it earlier.",
              "- Compositions run sequentially in fixed order, with separate warmup and fresh shield state. "
              "This is a scenario demonstration, not an A–B performance acceptance experiment. Shared runners, timer resolution, "
              "GC, and process scheduling affect latency. No latency threshold gates CI.",
              "- Percentiles use nearest rank. Short smoke runs have small samples and exist to validate accounting and cleanup. "
              "The simulator omits sockets, serialization, server queues, database locks, and real cancellation delays.", "",
              "## Environment and raw results", "",
              f"- {data['operatingSystem']}; {data['runtime']}; {data['architecture']}; {data['processorCount']} visible processors.",
              "- [Current published JSON](/Kevlar/measurements/outage-results.json) accompanies this page. "
              "The [outage workflow](https://github.com/thomhurst/Kevlar/actions/workflows/outage.yml) also uploads JSON and Markdown results for each run. "
              "JSON records all configuration, scheduled phase boundaries, actual phase attempt counts, and wall duration for each composition.", "",
              "## Reproduce", "", "```bash",
              "dotnet run -c Release --project benchmarks/Kevlar.OutageTests -- --phase-seconds 30 --rate 100 --max-inflight 512",
              "python .github/scripts/outage_docs.py --input artifacts/outage/outage-results.json --output artifacts/outage/outage-results.md",
              "```", "",
              "Use `--phase-seconds 1` for smoke validation. Scheduled/manual runs use 30 seconds per phase. "
              "For sustained throughput and allocation measurements, see [stress tests](stress-tests.md).", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    data = json.loads(Path(args.input).read_text(encoding="utf-8"))
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_page(data), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
