"""Generate the stress-test documentation page from a JSON run result."""

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


def fmt_count(value):
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    if value >= 1_000:
        return f"{value / 1_000:.2f}K"
    return str(value)


def fmt_bytes(value):
    if value >= 1024**3:
        return f"{value / 1024**3:.2f} GiB"
    if value >= 1024**2:
        return f"{value / 1024**2:.2f} MiB"
    if value >= 1024:
        return f"{value / 1024:.2f} KiB"
    return f"{value:.2f} B"


def fmt_duration(value):
    match = re.fullmatch(r"(?:(\d+)\.)?(\d{2}):(\d{2}):(\d{2}(?:\.\d+)?)", value)
    if match is None:
        raise ValueError(f"Invalid TimeSpan value: {value}")

    days, hours, minutes, seconds = match.groups(default="0")
    total_seconds = (
        int(days) * 86_400 + int(hours) * 3600 + int(minutes) * 60 + float(seconds)
    )
    if total_seconds >= 60:
        return f"{total_seconds / 60:g} minutes"
    return f"{total_seconds:g} seconds"


def build_page(data, commit):
    results = {result["library"]: result for result in data["results"]}
    if set(results) != {"Kevlar", "Polly"}:
        raise ValueError("Expected exactly one Kevlar result and one Polly result")

    kevlar = results["Kevlar"]
    polly = results["Polly"]
    throughput_ratio = kevlar["operationsPerSecond"] / polly["operationsPerSecond"]
    timestamp = datetime.fromisoformat(data["timestamp"]).strftime("%Y-%m-%d %H:%M UTC")
    run_commit = commit or data.get("commit", "")[:7]
    suffix = f" (commit `{run_commit}`)" if run_commit else ""

    lines = [
        "---",
        "sidebar_position: 13",
        "sidebar_label: Stress Tests",
        "---",
        "",
        "<!-- Auto-generated by .github/scripts/stress_docs.py — do not edit by hand. -->",
        "",
        "# Stress tests",
        "",
        "Kevlar and [Polly v8](https://github.com/App-vNext/Polly) run the same composed timeout, retry, and circuit-breaker workload under sustained parallel load. Alternating measurement rounds run in a single process, so they use the same GitHub runner while balancing early- and late-run conditions.",
        "",
        f"*Last updated {timestamp}{suffix}.*",
        "",
        ":::note",
        "Shared CI runners vary. Treat one run as a sustained-load health check, not a universal capacity claim. Compare ratios and allocation behavior, then measure your own workload.",
        ":::",
        "",
        "## Latest result",
        "",
        "| Library | Throughput | Operations | Allocated | Allocated/op | Managed heap (before / after) | GC collections (0 / 1 / 2) |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]

    for library in ("Kevlar", "Polly"):
        result = results[library]
        lines.append(
            f"| {library} | {fmt_count(result['operationsPerSecond'])} ops/s | "
            f"{fmt_count(result['operations'])} | {fmt_bytes(result['allocatedBytes'])} | "
            f"{result['bytesPerOperation']:.2f} B | "
            f"{fmt_bytes(result['managedBytesBefore'])} / {fmt_bytes(result['managedBytesAfter'])} | "
            f"{result['gen0Collections']} / "
            f"{result['gen1Collections']} / {result['gen2Collections']} |"
        )

    lines += [
        "",
        f"Kevlar completed **{throughput_ratio:.2f}×** as many operations per second as Polly in this run.",
        "",
        "## Method",
        "",
        f"- {data['workers']} parallel workers; "
        f"{fmt_duration(data['totalDuration'])} total measured time, split equally "
        f"between libraries across {data.get('measurementRounds', 1)} alternating rounds.",
        f"- Each pipeline warmed for {fmt_duration(data['warmup'])} before measurement.",
        "- Each operation returns `42` successfully through Timeout(10 s) → Retry(3, no delay) → CircuitBreaker(10% over 30 s, min 100, break 5 s).",
        "- Process-wide allocation counters include all worker threads. GC counts are captured separately for each phase.",
        f"- Peak working set for the shared process: {fmt_bytes(data['peakWorkingSetBytes'])}.",
        "",
        "## Environment",
        "",
        f"- {data['operatingSystem']}",
        f"- {data['runtime']}",
        f"- {data['processorCount']} logical processors visible to .NET",
        "",
        "## Reproduce",
        "",
        "```bash",
        "dotnet run -c Release --project benchmarks/Kevlar.StressTests -- --duration 00:15:00",
        "```",
        "",
        "Use `--workers`, `--warmup`, and `--output` to override the defaults. The [stress workflow](https://github.com/thomhurst/Kevlar/actions/workflows/stress.yml) runs weekly and republishes this page.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True)
    parser.add_argument("--commit", default="")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as source:
        data = json.load(source)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_page(data, args.commit), encoding="utf-8", newline="\n")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
