"""Generate the stress-test documentation page from a JSON run result."""

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


def fmt_count(value):
    if value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    if value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    if value >= 1_000:
        return f"{value / 1_000:.2f}K"
    return str(value)


def fmt_bytes(value):
    if value >= 1024**3:
        return f"{value / 1024**3:.2f} GiB"
    if value >= 1024**2:
        return f"{value / 1024**2:.2f} MiB"
    if value >= 1024:
        return f"{value / 1024:.2f} KiB"
    return f"{value:.2f} B"


def fmt_duration(value):
    match = re.fullmatch(r"(?:(\d+)\.)?(\d{2}):(\d{2}):(\d{2}(?:\.\d+)?)", value)
    if match is None:
        raise ValueError(f"Invalid TimeSpan value: {value}")

    days, hours, minutes, seconds = match.groups(default="0")
    total_seconds = (
        int(days) * 86_400 + int(hours) * 3600 + int(minutes) * 60 + float(seconds)
    )
    if total_seconds >= 60:
        return f"{total_seconds / 60:g} minutes"
    if total_seconds == 1:
        return "1 second"
    return f"{total_seconds:g} seconds"


def fmt_seconds(value):
    if value >= 1:
        return f"{value:.2f} s"
    return f"{value * 1000:.2f} ms"


SCENARIO_LABELS = {
    "SharedRatioPipeline": "Shared timeout → retry → ratio breaker",
    "TimeoutRetryPipeline": "Shared timeout → retry",
    "PerWorkerRatioPipeline": "Per-worker timeout → retry → ratio breaker",
}


def build_page(data, commit):
    results = data["results"]
    worker_counts = sorted({result["workers"] for result in results})
    workers_description = " and ".join(str(workers) for workers in worker_counts)
    grouped = {}
    for result in results:
        key = (result["scenario"], result["workers"])
        grouped.setdefault(key, {})[result["library"]] = result

    if not grouped or any(set(pair) != {"Kevlar", "Polly"} for pair in grouped.values()):
        raise ValueError("Expected one Kevlar and one Polly result per scenario")

    timestamp = datetime.fromisoformat(data["timestamp"]).strftime("%Y-%m-%d %H:%M UTC")
    run_commit = commit or data.get("commit", "")[:7]
    suffix = f" (commit `{run_commit}`)" if run_commit else ""

    lines = [
        "---",
        "sidebar_position: 19",
        "sidebar_label: Stress Tests",
        "---",
        "",
        "<!-- Auto-generated by .github/scripts/stress_docs.py — do not edit by hand. -->",
        "",
        "# Stress tests",
        "",
        "Kevlar and [Polly v8](https://github.com/App-vNext/Polly) run the same composed timeout, retry, and circuit-breaker workload under sustained parallel load. Alternating measurement rounds run in a single process, so they use the same GitHub runner while balancing early- and late-run conditions.",
        "",
        f"*Last updated {timestamp}{suffix}.*",
        "",
        ":::note",
        "Shared CI runners vary. Treat one run as a sustained-load health check, not a universal capacity claim. Compare ratios and allocation behavior, then measure your own workload.",
        ":::",
        "",
        "## Latest result",
        "",
        "| Scenario | Workers | Library | Throughput | CPU | Allocated | Allocated/op | GC pause | GC collections (0 / 1 / 2) | Process lock contentions |",
        "|---|---:|---|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for (scenario, workers), pair in grouped.items():
        for library in ("Kevlar", "Polly"):
            result = pair[library]
            cpu = result["cpuSeconds"] / result["elapsedSeconds"] * 100
            lines.append(
                f"| {SCENARIO_LABELS.get(scenario, scenario)} | {workers} | {library} | "
                f"{fmt_count(result['operationsPerSecond'])} ops/s | {cpu:.0f}% | "
                f"{fmt_bytes(result['allocatedBytes'])} | {result['bytesPerOperation']:.2f} B | "
                f"{fmt_seconds(result['gcPauseSeconds'])} | "
                f"{result['gen0Collections']} / "
                f"{result['gen1Collections']} / {result['gen2Collections']} | "
                f"{fmt_count(result['lockContentions'])} |"
            )

    lines += [
        "",
        "## Comparisons",
        "",
        "| Scenario | Workers | Kevlar / Polly throughput |",
        "|---|---:|---:|",
    ]

    for (scenario, workers), pair in grouped.items():
        ratio = pair["Kevlar"]["operationsPerSecond"] / pair["Polly"]["operationsPerSecond"]
        lines.append(
            f"| {SCENARIO_LABELS.get(scenario, scenario)} | {workers} | **{ratio:.2f}×** |"
        )

    lines += [
        "",
        "## Method",
        "",
        f"- {workers_description} parallel workers; "
        f"{fmt_duration(data['totalDuration'])} total measured time, split equally "
        f"between scenarios and libraries across {data.get('measurementRounds', 1)} alternating rounds.",
        f"- Each scenario and library warmed for {fmt_duration(data['warmup'])} before measurement.",
        "- Shared and per-worker ratio-breaker scenarios run Timeout(10 s) → Retry(3, no delay) → CircuitBreaker(10% over 30 s, min 100, break 5 s).",
        "- Timeout/retry isolates pipeline overhead from circuit-breaker shared-state contention.",
        "- Process-wide CPU, allocation, GC pause, collection, and managed-lock contention counters are captured separately for each phase.",
        f"- Peak working set for the shared process: {fmt_bytes(data['peakWorkingSetBytes'])}.",
        "",
        "## Environment",
        "",
        f"- {data['operatingSystem']}",
        f"- {data['runtime']}",
        f"- {data['processorCount']} logical processors visible to .NET",
        "",
        "## Reproduce",
        "",
        "```bash",
        "dotnet run -c Release --project benchmarks/Kevlar.StressTests -- --duration 00:15:00",
        "```",
        "",
        "Use `--workers`, `--warmup`, and `--output` to override the defaults. The [stress workflow](https://github.com/thomhurst/Kevlar/actions/workflows/stress.yml) runs weekly and republishes this page.",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True)
    parser.add_argument("--commit", default="")
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.input, encoding="utf-8") as source:
        data = json.load(source)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_page(data, args.commit), encoding="utf-8", newline="\n")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
