<Project>

  <Target Name="PinKevlarDependencyVersion"
          AfterTargets="_GetProjectReferenceVersions"
          Condition="'$(PinKevlarDependencyVersion)' == 'true'">
    <ItemGroup>
      <_ProjectReferencesWithVersions Update="@(_ProjectReferencesWithVersions)"
                                      Condition="'%(Filename)' == 'Kevlar'">
        <ProjectVersion>[%(_ProjectReferencesWithVersions.ProjectVersion)]</ProjectVersion>
      </_ProjectReferencesWithVersions>
    </ItemGroup>
  </Target>

</Project>
