<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Tom Longhurst</Authors>
    <Copyright>Copyright (c) Tom Longhurst 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/thomhurst/Kevlar</RepositoryUrl>
    <PackageProjectUrl>https://github.com/thomhurst/Kevlar</PackageProjectUrl>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
