<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kevlar" VersionOverride="$(KevlarPackageVersion)" />
    <PackageReference Include="Kevlar.Analyzers" VersionOverride="$(KevlarPackageVersion)" PrivateAssets="all" />
    <PackageReference Include="Kevlar.Extensions.DependencyInjection" VersionOverride="$(KevlarPackageVersion)" />
    <PackageReference Include="Kevlar.Extensions.Http" VersionOverride="$(KevlarPackageVersion)" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(GeneratedSnippetsPath)" Link="GeneratedSnippets.g.cs" />
  </ItemGroup>

</Project>
