<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Condition="'$(UsePackedPackages)' != 'true'">
    <ProjectReference Include="..\..\src\Kevlar\Kevlar.csproj" />
    <ProjectReference Include="..\..\src\Kevlar.Chaos\Kevlar.Chaos.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UsePackedPackages)' == 'true'">
    <PackageReference Include="Kevlar" VersionOverride="$(KevlarSamplePackageVersion)" />
    <PackageReference Include="Kevlar.Chaos" VersionOverride="$(KevlarSamplePackageVersion)" />
  </ItemGroup>
</Project>
