<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.RateLimiting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kevlar.Chaos\Kevlar.Chaos.csproj" />
    <ProjectReference Include="..\..\src\Kevlar\Kevlar.csproj" />
    <ProjectReference Include="..\..\src\Kevlar.Extensions.DependencyInjection\Kevlar.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Kevlar.Extensions.Http\Kevlar.Extensions.Http.csproj" />
  </ItemGroup>

</Project>
