using System.Collections.Immutable;
using Kevlar.Analyzers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Kevlar.Analyzers.Tests;

/// <summary>
/// Guards KEV001: execution delegates that ignore the CancellationToken they are handed are
/// flagged; delegates that use it — and Execute-named methods outside Kevlar — are not.
/// </summary>
public class IgnoredCancellationTokenTests
{
    private static readonly string[] IgnoredExecutionOverloadCases =
    [
        "var result = Shield.Empty.Execute(ct => 1);",
        "var result = Shield.Empty.Execute(1, (state, ct) => state);",
        "Shield.Empty.Execute(ct => { });",
        "Shield.Empty.Execute(1, (state, ct) => { _ = state; });",
        "await Shield.Empty.ExecuteAsync(ct => new ValueTask<int>(1));",
        "await Shield.Empty.ExecuteAsync(1, (state, ct) => new ValueTask<int>(state));",
        "await Shield.Empty.ExecuteAsync(ct => ValueTask.CompletedTask);",
        "await Shield.Empty.ExecuteAsync(1, (state, ct) => { _ = state; return ValueTask.CompletedTask; });",
        "await Shield.Empty.ExecuteOutcomeAsync(ct => new ValueTask<int>(1));",
        "await Shield.Empty.ExecuteAsync(ct => Task.FromResult(1));",
        "await Shield.Empty.ExecuteAsync(1, (state, ct) => Task.FromResult(state));",
        "await Shield.Empty.ExecuteAsync(ct => Task.CompletedTask);",
        "await Shield.Empty.ExecuteAsync(1, (state, ct) => { _ = state; return Task.CompletedTask; });",
        "await Shield.Empty.ExecuteOutcomeAsync(ct => Task.FromResult(1));",
        "var result = Shield<int>.Empty.Execute(ct => 1);",
        "var result = Shield<int>.Empty.Execute(1, (state, ct) => state);",
        "await Shield<int>.Empty.ExecuteAsync(ct => new ValueTask<int>(1));",
        "await Shield<int>.Empty.ExecuteAsync(1, (state, ct) => new ValueTask<int>(state));",
        "await Shield<int>.Empty.ExecuteOutcomeAsync(ct => new ValueTask<int>(1));",
        "await Shield<int>.Empty.ExecuteAsync(ct => Task.FromResult(1));",
        "await Shield<int>.Empty.ExecuteAsync(1, (state, ct) => Task.FromResult(state));",
        "await Shield<int>.Empty.ExecuteOutcomeAsync(ct => Task.FromResult(1));",
    ];

    private static Task<ImmutableArray<Diagnostic>> AnalyzeAsync(string body) =>
        AnalyzeSourceAsync($$"""
            public class TestSubject
            {
                public async Task RunAsync()
                {
                    {{body}}
                }
            }
            """);

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeSourceAsync(
        string declarations,
        bool allowCompilationErrors = false,
        bool isGenerated = false)
    {
        var source = CreateSource(declarations, isGenerated);
        var compilation = CreateCompilation(source);

        var compileErrors = compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        if (!allowCompilationErrors && compileErrors.Count > 0)
        {
            throw new InvalidOperationException("Test source does not compile: " + string.Join("; ", compileErrors));
        }

        return await GetAnalyzerDiagnosticsAsync(compilation);
    }

    private static string CreateSource(string declarations, bool isGenerated = false) =>
        (isGenerated ? "// <auto-generated/>\n" : string.Empty) + $$"""
            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using Kevlar;

            {{declarations}}
            """;

    private static CSharpCompilation CreateCompilation(string source)
    {
        var references = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator)
            .Select(path => (MetadataReference)MetadataReference.CreateFromFile(path))
            .Append(MetadataReference.CreateFromFile(typeof(Shield).Assembly.Location))
            .ToList();

        return CSharpCompilation.Create(
            "AnalyzerTestSubject",
            [CSharpSyntaxTree.ParseText(source)],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    private static Task<ImmutableArray<Diagnostic>> GetAnalyzerDiagnosticsAsync(CSharpCompilation compilation) =>
        compilation
            .WithAnalyzers(ImmutableArray.Create<DiagnosticAnalyzer>(new IgnoredCancellationTokenAnalyzer()))
            .GetAnalyzerDiagnosticsAsync();

    private static async Task AssertDiagnosticCountAsync(
        IEnumerable<string> cases,
        int expectedCount,
        string caseKind)
    {
        foreach (var body in cases)
        {
            var diagnostics = await AnalyzeAsync(body);
            if (diagnostics.Length != expectedCount)
            {
                throw new InvalidOperationException(
                    $"Expected {expectedCount} KEV001 diagnostic(s) for {caseKind} case '{body}', but found {diagnostics.Length}.");
            }
        }
    }

    [Test]
    public async Task A_Lambda_That_Ignores_The_Token_Is_Flagged()
    {
        var diagnostics = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(ct => new ValueTask<int>(1));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(1);
        await Assert.That(diagnostics[0].Id).IsEqualTo("KEV001");
    }

    [Test]
    public async Task A_Lambda_That_Uses_The_Token_Is_Clean()
    {
        var diagnostics = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(async ct => { await Task.Delay(1, ct); return 1; });
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task An_Underscore_Token_Explicitly_Suppresses_The_Diagnostic()
    {
        var diagnostics = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(_ => new ValueTask<int>(1));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task The_Task_Extension_Overloads_Are_Covered_Too()
    {
        var diagnostics = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(ct => Task.FromResult(1));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(1);
        await Assert.That(diagnostics[0].Id).IsEqualTo("KEV001");
    }

    [Test]
    public async Task State_Threading_Overloads_Are_Analyzed()
    {
        var flagged = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(5, (state, ct) => new ValueTask<int>(state));
            """);
        await Assert.That(flagged.Length).IsEqualTo(1);

        var clean = await AnalyzeAsync("""
            var shield = Shield.Retry(1);
            await shield.ExecuteAsync(5, async (state, ct) => { await Task.Delay(state, ct); return state; });
            """);
        await Assert.That(clean.Length).IsEqualTo(0);
    }

    [Test]
    public async Task Typed_Shields_Are_Analyzed()
    {
        var diagnostics = await AnalyzeAsync("""
            var shield = Shield.For<int>().WhenResult(0).Retry(1);
            await shield.ExecuteAsync(ct => new ValueTask<int>(1));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(1);
    }

    [Test]
    public async Task Execute_Methods_Outside_Kevlar_Are_Ignored()
    {
        var diagnostics = await AnalyzeSourceAsync("""
            public static class OtherExecutor
            {
                public static Task<T> ExecuteAsync<T>(Func<CancellationToken, Task<T>> action) => action(CancellationToken.None);
            }

            public class TestSubject
            {
                public async Task RunAsync() => await OtherExecutor.ExecuteAsync(ct => Task.FromResult(1));
            }
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task Every_Public_Execution_Overload_Is_Analyzed()
    {
        var publicOverloadCount = new[]
        {
            typeof(Shield),
            typeof(Shield<>),
            typeof(ShieldTaskExtensions),
        }.Sum(type => type
            .GetMethods(System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.Static
                | System.Reflection.BindingFlags.DeclaredOnly)
            .Count(method => method.Name is "Execute" or "ExecuteAsync" or "ExecuteOutcomeAsync"));

        await Assert.That(IgnoredExecutionOverloadCases.Length).IsEqualTo(publicOverloadCount);
        await AssertDiagnosticCountAsync(IgnoredExecutionOverloadCases, 1, "public execution overload");
    }

    [Test]
    public async Task Lambda_Syntax_Forms_Are_Analyzed()
    {
        var cases = new[]
        {
            "var result = Shield.Empty.Execute(ct => 1);",
            "var result = Shield.Empty.Execute(ct => { return 1; });",
            "var result = Shield.Empty.Execute((CancellationToken ct) => 1);",
            "await Shield.Empty.ExecuteAsync(async ct => { await Task.Yield(); return 1; });",
            "Shield.Empty.Execute(delegate(CancellationToken ct) { });",
        };

        await AssertDiagnosticCountAsync(cases, 1, "lambda syntax");
    }

    [Test]
    public async Task Semantic_Token_Uses_Are_Clean()
    {
        var cases = new[]
        {
            "var result = Shield.Empty.Execute(ct => ct.CanBeCanceled ? 1 : 0);",
            "Shield.Empty.Execute(ct => { _ = ct; });",
            "await Shield.Empty.ExecuteAsync(ct => new ValueTask<int>(ct.GetHashCode()));",
            "await Shield.Empty.ExecuteAsync(async ct => { await Task.Delay(1, ct); });",
            "await Shield.Empty.ExecuteAsync(1, (state, ct) => Task.Delay(state, ct));",
            "await Shield.Empty.ExecuteOutcomeAsync(ct => Task.FromResult(ct.GetHashCode()));",
            "var result = Shield<int>.Empty.Execute(ct => ct.GetHashCode());",
            "await Shield<int>.Empty.ExecuteAsync(1, (state, ct) => Task.FromResult(state + ct.GetHashCode()));",
        };

        await AssertDiagnosticCountAsync(cases, 0, "token use");
    }

    [Test]
    public async Task Token_Use_Through_A_Local_Function_Is_Clean()
    {
        var diagnostics = await AnalyzeAsync("""
            await Shield.Empty.ExecuteAsync(ct =>
            {
                int ReadToken() => ct.GetHashCode();
                return new ValueTask<int>(ReadToken());
            });
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task A_Nested_Lambda_Does_Not_Mistake_Its_Own_Token_For_The_Execution_Token()
    {
        var diagnostics = await AnalyzeAsync("""
            await Shield.Empty.ExecuteAsync(ct => new ValueTask<int>(
                new Func<CancellationToken, int>(innerCt => innerCt.GetHashCode())(default)));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(1);
    }

    [Test]
    public async Task Execution_Token_Captured_By_A_Nested_Lambda_Is_Clean()
    {
        var diagnostics = await AnalyzeAsync("""
            await Shield.Empty.ExecuteAsync(ct => new ValueTask<int>(
                new Func<int>(() => ct.GetHashCode())()));
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task Method_Groups_Are_Ignored()
    {
        var diagnostics = await AnalyzeSourceAsync("""
            public class TestSubject
            {
                public int Run() => Shield.Empty.Execute(Work);

                private static int Work(CancellationToken cancellationToken) => 1;
            }
            """);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task Generated_Code_Is_Ignored()
    {
        var diagnostics = await AnalyzeSourceAsync("""
            public class TestSubject
            {
                public int Run() => Shield.Empty.Execute(ct => 1);
            }
            """, isGenerated: true);

        await Assert.That(diagnostics.Length).IsEqualTo(0);
    }

    [Test]
    public async Task Diagnostic_Contract_And_Location_Are_Exact()
    {
        const string lambda = "ct => 1";
        const string declarations = """
            public class TestSubject
            {
                public int Run() => Shield.Empty.Execute(ct => 1);
            }
            """;
        var source = CreateSource(declarations);
        var diagnostics = await GetAnalyzerDiagnosticsAsync(CreateCompilation(source));

        await Assert.That(diagnostics.Length).IsEqualTo(1);
        var diagnostic = diagnostics[0];
        await Assert.That(diagnostic.Id).IsEqualTo("KEV001");
        await Assert.That(diagnostic.Severity).IsEqualTo(DiagnosticSeverity.Warning);
        await Assert.That(diagnostic.GetMessage()).IsEqualTo(
            "The delegate passed to 'Execute' never uses the CancellationToken it is handed; timeouts and cancellation cannot stop it. Pass the token to the work inside, or name it '_' only if the work is truly uncancellable.");
        await Assert.That(diagnostic.Location.SourceSpan.Start).IsEqualTo(source.IndexOf(lambda, StringComparison.Ordinal));
        await Assert.That(diagnostic.Location.SourceSpan.Length).IsEqualTo(lambda.Length);
    }

    [Test]
    public async Task Malformed_Compilation_Does_Not_Crash_The_Analyzer()
    {
        var diagnostics = await AnalyzeSourceAsync("""
            public class TestSubject
            {
                public async Task RunAsync()
                {
                    await Shield.Empty.ExecuteAsync(ct =>
                }
            }
            """, allowCompilationErrors: true);

        await Assert.That(diagnostics.Any(diagnostic => diagnostic.Id == "AD0001")).IsFalse();
    }

    [Test]
    public async Task Concurrent_Analyzer_Runs_Are_Deterministic()
    {
        var source = CreateSource("""
            public class TestSubject
            {
                public async Task RunAsync()
                {
                    Shield.Empty.Execute(ct => { });
                    await Shield.Empty.ExecuteAsync(ct => Task.CompletedTask);
                    await Shield<int>.Empty.ExecuteOutcomeAsync(ct => new ValueTask<int>(1));
                }
            }
            """);
        var compilation = CreateCompilation(source);
        var runs = await Task.WhenAll(Enumerable.Range(0, 16)
            .Select(_ => GetAnalyzerDiagnosticsAsync(compilation)));
        var expected = runs[0]
            .Select(diagnostic => diagnostic.Location.SourceSpan)
            .OrderBy(span => span.Start)
            .ToArray();

        await Assert.That(expected.Length).IsEqualTo(3);
        foreach (var run in runs)
        {
            var actual = run
                .Select(diagnostic => diagnostic.Location.SourceSpan)
                .OrderBy(span => span.Start)
                .ToArray();
            if (!expected.SequenceEqual(actual))
            {
                throw new InvalidOperationException("Concurrent analyzer runs produced different diagnostic spans.");
            }
        }
    }
}
