[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$PackagesPath,

    [Parameter(Mandatory)]
    [string]$Version,

    [switch]$NoImplicitUsings
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path $PSScriptRoot -Parent
$resolvedPackagesPath = (Resolve-Path -LiteralPath $PackagesPath).Path
$generatedDirectory = Join-Path $repositoryRoot 'artifacts/doc-tests/generated'
$generatedPath = Join-Path $generatedDirectory 'DocumentationSnippets.cs'
$nugetConfigPath = Join-Path $generatedDirectory 'NuGet.config'
$projectPath = Join-Path $repositoryRoot 'tests/Kevlar.DocTests/Kevlar.DocTests.csproj'
$documentPaths = @(
    (Join-Path $repositoryRoot 'README.md')
    Get-ChildItem (Join-Path $repositoryRoot 'src') -Directory |
        ForEach-Object { Join-Path $_.FullName 'README.md' } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        Sort-Object
    Get-ChildItem (Join-Path $repositoryRoot 'docs/docs') -Recurse -File -Include '*.md', '*.mdx' |
        Sort-Object FullName |
        ForEach-Object FullName
)

$requiredPackages = @(
    'Kevlar'
    'Kevlar.Chaos'
    'Kevlar.Extensions.DependencyInjection'
    'Kevlar.Extensions.Grpc'
    'Kevlar.Extensions.Http'
    'Kevlar.Extensions.Logging'
    'Kevlar.Extensions.RateLimiting'
    'Kevlar.Testing'
)
$allowedExternalPackages = @(
    'Microsoft.Extensions.Configuration.Json'
    'Microsoft.Extensions.TimeProvider.Testing'
)
$supportedDiagnosticIds = [System.Collections.Generic.HashSet[string]]::new(
    [string[]]@(
        'KEV001', 'KEV002', 'KEV003', 'KEV004', 'KEV005', 'KEV006', 'KEV007'
        'KEV008', 'KEV012', 'KEV014'
    ),
    [StringComparer]::Ordinal)
$forbiddenDocumentationPatterns = [ordered]@{
    'doc-test-ignore' = 'doc-test-ignore'
    'warning pragma' = '(?m)^\s*#pragma\s+warning\s+disable\b'
    'disabled nullable warnings' = '(?im)^\s*#nullable\s+disable\b|(?is)<Nullable\b[^>]*>\s*(?:disable|annotations)\s*</Nullable>'
    'NoWarn' = '(?i)<NoWarn\b'
    'WarningsNotAsErrors' = '(?i)\bWarningsNotAsErrors\b'
    'disabled diagnostic severity' = '(?i)(?:dotnet_diagnostic\.[^.\s=]+|dotnet_analyzer_diagnostic(?:\.category-[^.\s=]+)?)\.severity\s*=\s*(?:none|silent)\b'
    'downgraded warning severity' = '(?i)(?:dotnet_diagnostic\.(?!KEV(?:009|010|011)\.severity\b)[^.\s=]+|dotnet_analyzer_diagnostic(?:\.category-[^.\s=]+)?)\.severity\s*=\s*suggestion\b'
    'disabled warnings-as-errors' = '(?is)<TreatWarningsAsErrors\b[^>]*>\s*false\s*</TreatWarningsAsErrors>'
    'disabled analyzer execution' = '(?is)<(?<property>EnableNETAnalyzers|RunAnalyzers|RunAnalyzersDuringBuild)\b[^>]*>\s*false\s*</\k<property>>'
    'disabled analyzer level' = '(?is)<(?<property>AnalysisLevel(?:[A-Za-z]+)?)\b[^>]*>\s*(?:(?:none|[0-3](?:\.[0-9]+)?|4(?:\.0+)?)(?:-[^<\s]+)?|[^<\s]+-none)\s*</\k<property>>'
    'disabled analyzer mode' = '(?is)<(?<property>AnalysisMode(?:[A-Za-z]+)?)\b[^>]*>\s*(?:none|AllDisabledByDefault)\s*</\k<property>>'
    'disabled compiler warnings' = '(?is)<WarningLevel\b[^>]*>\s*0\s*</WarningLevel>'
    'excluded Kevlar analyzers' = '(?is)<PackageReference\b(?=[^>]*\b(?:Include|Update)\s*=\s*["'']Kevlar["''])(?=[^>]*\bExcludeAssets\s*=\s*["''][^"'']*\banalyzers\b)[^>]*>'
    'excluded Kevlar analyzer metadata' = '(?is)<PackageReference\b(?=[^>]*\b(?:Include|Update)\s*=\s*["'']Kevlar["''])[^>]*>.*?<ExcludeAssets\b[^>]*>[^<]*\banalyzers\b[^<]*</ExcludeAssets>.*?</PackageReference>'
    'generated-code marker' = '(?i)<auto-generated(?:\s|/|>)'
    'generated-code setting' = '(?im)^\s*generated_code\s*=\s*true\b'
}

$harnessPaths = @(
    $projectPath
    (Join-Path $repositoryRoot 'tests/Kevlar.DocTests/Program.cs')
)
$configurationDirectory = Get-Item -LiteralPath (Split-Path $projectPath -Parent)
while ($configurationDirectory.FullName.StartsWith($repositoryRoot, [StringComparison]::OrdinalIgnoreCase))
{
    foreach ($configurationName in @(
        'Directory.Build.props'
        'Directory.Build.targets'
        '.editorconfig'
        '.globalconfig'
    ))
    {
        $configurationPath = Join-Path $configurationDirectory.FullName $configurationName
        if (Test-Path -LiteralPath $configurationPath -PathType Leaf)
        {
            $harnessPaths += $configurationPath
        }
    }

    $configurationDirectory = $configurationDirectory.Parent
}

foreach ($harnessPath in $harnessPaths)
{
    $harnessText = Get-Content -Raw -LiteralPath $harnessPath
    foreach ($forbiddenPattern in $forbiddenDocumentationPatterns.GetEnumerator())
    {
        if ($harnessText -match $forbiddenPattern.Value)
        {
            $relativeHarnessPath = [IO.Path]::GetRelativePath($repositoryRoot, $harnessPath)
            throw "Documentation harness contains forbidden $($forbiddenPattern.Key) in $relativeHarnessPath."
        }
    }
}

foreach ($packageId in $requiredPackages)
{
    $packagePath = Join-Path $resolvedPackagesPath "$packageId.$Version.nupkg"
    if (-not (Test-Path -LiteralPath $packagePath -PathType Leaf))
    {
        throw "Documented package '$packageId' was not packed at '$packagePath'."
    }

    $packageReadmePath = Join-Path $repositoryRoot "src/$packageId/README.md"
    if (-not (Test-Path -LiteralPath $packageReadmePath -PathType Leaf))
    {
        throw "Documented package '$packageId' has no package-specific README at '$packageReadmePath'."
    }
}

$snippets = [System.Collections.Generic.List[object]]::new()
$projectFragments = [System.Collections.Generic.List[object]]::new()
$installPackageIds = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$projectCommands = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)

foreach ($documentPath in $documentPaths)
{
    $relativePath = [IO.Path]::GetRelativePath($repositoryRoot, $documentPath).Replace('\', '/')
    $lines = Get-Content -LiteralPath $documentPath
    $documentText = $lines -join "`n"
    foreach ($forbiddenPattern in $forbiddenDocumentationPatterns.GetEnumerator())
    {
        if ($documentText -match $forbiddenPattern.Value)
        {
            throw "Documentation contains forbidden $($forbiddenPattern.Key) in $relativePath."
        }
    }

    $lineOffset = 0
    $csharpOrdinal = 0

    for ($lineIndex = 0; $lineIndex -lt $lines.Count; $lineIndex++)
    {
        if ($lines[$lineIndex] -match '^```csharp\s*$')
        {
            $csharpOrdinal++
            $startLine = $lineOffset + $lineIndex + 2
            $directive = if ($lineIndex -gt 0) { $lines[$lineIndex - 1].Trim() } else { '' }
            $body = [System.Collections.Generic.List[string]]::new()
            for ($lineIndex++; $lineIndex -lt $lines.Count -and $lines[$lineIndex] -notmatch '^```\s*$'; $lineIndex++)
            {
                $body.Add($lines[$lineIndex])
            }

            if ($lineIndex -ge $lines.Count)
            {
                throw "Unclosed C# fence at ${relativePath}:$startLine."
            }

            $mode = 'statements'
            $splitBefore = $null
            $runName = $null
            $expectedDiagnostics = [System.Collections.Generic.List[object]]::new()
            $diagnosticText = $null
            if ($directive -match '^<!--\s*doc-test-run:\s*([a-z0-9-]+)\s*-->$')
            {
                $runName = $Matches[1]
            }
            elseif ($directive -match '^<!--\s*doc-test-diagnostic:\s*(.+?)\s*-->$')
            {
                $diagnosticText = $Matches[1]
            }

            if ($null -ne $diagnosticText)
            {
                foreach ($diagnosticSpec in $diagnosticText -split ',')
                {
                    if ($diagnosticSpec.Trim() -notmatch '^(KEV[0-9]{3})(?:\*([1-9][0-9]*))?$')
                    {
                        throw "Malformed diagnostic '$diagnosticSpec' before ${relativePath}:$startLine. Use KEVnnn or KEVnnn*count."
                    }

                    if (-not $supportedDiagnosticIds.Contains($Matches[1]))
                    {
                        throw "Unsupported Kevlar diagnostic '$($Matches[1])' before ${relativePath}:$startLine."
                    }

                    $diagnosticCount = if ($Matches[2]) { [int]$Matches[2] } else { 1 }
                    $expectedDiagnostics.Add([pscustomobject]@{
                        Id = $Matches[1]
                        Count = $diagnosticCount
                    })
                }
            }

            if ($directive -match '^<!--\s*doc-test-declaration:\s*split-before=(.+?)\s*-->$')
            {
                $mode = 'declaration'
                $splitBefore = $Matches[1]
            }
            elseif ($directive -match '^<!--\s*doc-test-tail-declaration:\s*split-before=(.+?)\s*-->$')
            {
                $mode = 'tail-declaration'
                $splitBefore = $Matches[1]
            }
            elseif ($directive -match '^<!--\s*doc-test-declaration\s*-->$')
            {
                $mode = 'declaration'
            }
            elseif ($directive -match '^<!--\s*doc-test-strategy-member\s*-->$')
            {
                $mode = 'strategy-member'
            }
            elseif ($directive -match '^<!--\s*doc-test-' `
                -and $null -eq $runName `
                -and $expectedDiagnostics.Count -eq 0)
            {
                throw "Unknown or malformed doc-test directive before ${relativePath}:$startLine."
            }

            $source = $body -join "`n"
            $snippetUsings = @(
                [regex]::Matches(
                    $source,
                    '(?m)^using\s+(?<namespace>[A-Za-z0-9_.]+);\s*(?://.*)?$') |
                    ForEach-Object { "using $($_.Groups['namespace'].Value);" } |
                    Where-Object { -not $_.StartsWith('using TUnit.', [StringComparison]::Ordinal) } |
                    Select-Object -Unique
            )

            $sourceWithoutLineComments = [regex]::Replace($source, '(?s)/\*.*?\*/', '') -replace '(?m)//.*$', ''
            if ($sourceWithoutLineComments -match '\.\.\.')
            {
                throw "Incomplete C# is forbidden at $relativePath#$csharpOrdinal."
            }

            $snippets.Add([pscustomobject]@{
                Id = "$relativePath#$csharpOrdinal"
                Path = $relativePath
                SourcePath = $documentPath.Replace('\', '/')
                Line = $startLine
                EndLine = $startLine + $body.Count - 1
                Source = $source
                Mode = $mode
                SplitBefore = $splitBefore
                RunName = $runName
                Usings = $snippetUsings
                ExpectedDiagnostics = $expectedDiagnostics
            })

            continue
        }

        if ($lines[$lineIndex] -match '^```xml\s*$')
        {
            $startLine = $lineOffset + $lineIndex + 2
            $directive = if ($lineIndex -gt 0) { $lines[$lineIndex - 1].Trim() } else { '' }
            $body = [System.Collections.Generic.List[string]]::new()
            for ($lineIndex++; $lineIndex -lt $lines.Count -and $lines[$lineIndex] -notmatch '^```\s*$'; $lineIndex++)
            {
                $body.Add($lines[$lineIndex])
            }

            if ($lineIndex -ge $lines.Count)
            {
                throw "Unclosed XML fence at ${relativePath}:$startLine."
            }

            if ($directive -eq '<!-- doc-test-project-fragment -->')
            {
                $source = $body -join "`n"
                try
                {
                    [xml]$fragment = "<Project>`n$source`n</Project>"
                }
                catch
                {
                    throw "Invalid MSBuild project fragment at ${relativePath}:$startLine. $($_.Exception.Message)"
                }

                $projectFragments.Add([pscustomobject]@{
                    Id = "${relativePath}:$startLine"
                    Xml = $fragment
                })
            }
            elseif ($directive -match '^<!--\s*doc-test-project-fragment')
            {
                throw "Malformed doc-test-project-fragment directive before ${relativePath}:$startLine."
            }

            continue
        }

        if ($lines[$lineIndex] -match '^```(?:bash|sh|shell|powershell|pwsh)\s*$')
        {
            for ($lineIndex++; $lineIndex -lt $lines.Count -and $lines[$lineIndex] -notmatch '^```\s*$'; $lineIndex++)
            {
                $command = $lines[$lineIndex].Trim()
                if ($command -match '^dotnet add package\s+([A-Za-z0-9_.-]+)')
                {
                    [void]$installPackageIds.Add($Matches[1])
                }

                if ($command -match '^dotnet run\s+.*--project\s+([^\s]+)')
                {
                    [void]$projectCommands.Add($Matches[1].Trim("'`""))
                }
            }
        }
    }
}

foreach ($projectFragment in $projectFragments)
{
    foreach ($packageReference in $projectFragment.Xml.SelectNodes('/Project/ItemGroup/PackageReference'))
    {
        $include = $packageReference.GetAttribute('Include')
        if ([string]::IsNullOrWhiteSpace($include))
        {
            throw "$($projectFragment.Id) contains a PackageReference without Include."
        }

        $excludeAssets = @(
            $packageReference.GetAttribute('ExcludeAssets') -split ';' |
                ForEach-Object { $_.Trim() })
        if ($include -eq 'Kevlar' -and
            $excludeAssets -contains 'analyzers')
        {
            throw "$($projectFragment.Id) excludes Kevlar analyzers; documentation must keep safety diagnostics enabled."
        }
    }
}

foreach ($packageId in $installPackageIds)
{
    if ($packageId -notin $requiredPackages -and $packageId -notin $allowedExternalPackages)
    {
        throw "Shell sample references unexpected package ID '$packageId'."
    }
}

foreach ($relativeProjectPath in $projectCommands)
{
    if (-not (Test-Path -LiteralPath (Join-Path $repositoryRoot $relativeProjectPath)))
    {
        throw "Shell sample references missing project '$relativeProjectPath'."
    }
}

$diagnosticSnippetCount = @(
    $snippets |
        Where-Object { $_.ExpectedDiagnostics.Count -gt 0 }
).Count
$warningCleanSnippetCount = $snippets.Count - $diagnosticSnippetCount
$expectedDiagnosticCount = ($snippets.ExpectedDiagnostics |
    Measure-Object -Property Count -Sum).Sum

New-Item -ItemType Directory -Force -Path $generatedDirectory | Out-Null

$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine('#nullable enable')
$usingStatements = @(
    'using System;'
    'using System.Collections.Generic;'
    'using System.Diagnostics.Metrics;'
    'using System.IO;'
    'using System.Linq;'
    'using System.Net;'
    'using System.Net.Http;'
    'using System.Threading;'
    'using System.Threading.Tasks;'
    'using Kevlar;'
    'using Microsoft.Extensions.Configuration;'
    'using Microsoft.Extensions.Time.Testing;'
    'using Microsoft.Extensions.Logging;'
    'using Microsoft.Extensions.Http.Resilience;'
    'using System.Threading.RateLimiting;'
    'using OpenTelemetry.Metrics;'
    'using Polly;'
    'using Polly.CircuitBreaker;'
    'using Polly.Hedging;'
    'using Polly.Retry;'
    'using Polly.Simmy;'
    'using Polly.Testing;'
    'using Polly.Timeout;'
)

if (-not $NoImplicitUsings)
{
    $usingStatements += @(
        'using Kevlar.Chaos;'
        'using Kevlar.Extensions.DependencyInjection;'
        'using Kevlar.Extensions.Grpc;'
        'using Kevlar.Extensions.Http;'
        'using Kevlar.Extensions.RateLimiting;'
        'using Kevlar.Testing;'
    )
}

foreach ($usingStatement in $usingStatements | Select-Object -Unique)
{
    [void]$builder.AppendLine($usingStatement)
}

for ($snippetIndex = 0; $snippetIndex -lt $snippets.Count; $snippetIndex++)
{
    $snippet = $snippets[$snippetIndex]
    $source = $snippet.Source -replace '(?m)^using\s+[A-Za-z0-9_.]+;\s*(?://.*)?$', ''
    $compilationCondition = if ($snippet.ExpectedDiagnostics.Count -gt 0)
    {
        'DOCUMENTATION_DIAGNOSTICS'
    }
    else
    {
        '!DOCUMENTATION_DIAGNOSTICS'
    }
    [void]$builder.AppendLine("#if $compilationCondition")
    [void]$builder.AppendLine('namespace Kevlar.DocTests')
    [void]$builder.AppendLine('{')
    foreach ($usingStatement in $snippet.Usings)
    {
        [void]$builder.AppendLine("    $usingStatement")
    }
    [void]$builder.AppendLine("internal sealed class Snippet$snippetIndex : SnippetContext")
    [void]$builder.AppendLine('{')

    if ($snippet.Mode -eq 'declaration')
    {
        if ($null -eq $snippet.SplitBefore)
        {
            $declarationSource = $source.TrimEnd()
            $source = ''
        }
        else
        {
            $splitIndex = $source.IndexOf($snippet.SplitBefore, [StringComparison]::Ordinal)
            if ($splitIndex -lt 0)
            {
                throw "Declaration split marker '$($snippet.SplitBefore)' was not found in $($snippet.Id)."
            }

            $declarationSource = $source.Substring(0, $splitIndex).TrimEnd()
            $source = $source.Substring($splitIndex)
        }
        [void]$builder.AppendLine("#line $($snippet.Line) `"$($snippet.SourcePath)`"")
        foreach ($line in ($declarationSource -split "`n"))
        {
            [void]$builder.AppendLine("    $line")
        }
        [void]$builder.AppendLine('#line default')
    }
    elseif ($snippet.Mode -eq 'strategy-member')
    {
        [void]$builder.AppendLine('    private sealed class DocumentationStrategy : Strategy')
        [void]$builder.AppendLine('    {')
        [void]$builder.AppendLine("#line $($snippet.Line) `"$($snippet.SourcePath)`"")
        foreach ($line in ($source -split "`n"))
        {
            [void]$builder.AppendLine("        $line")
        }
        [void]$builder.AppendLine('#line default')
        if ($source -notmatch '\bExecuteAsync\b')
        {
            [void]$builder.AppendLine('        public override ValueTask<Outcome<T>> ExecuteAsync<T, TState>(')
            [void]$builder.AppendLine('            Continuation<T, TState> next, KevlarContext context) =>')
            [void]$builder.AppendLine('            next.InvokeAsync(context);')
        }
        [void]$builder.AppendLine('    }')
        $source = ''
    }
    elseif ($snippet.Mode -eq 'tail-declaration')
    {
        $splitIndex = $source.IndexOf($snippet.SplitBefore, [StringComparison]::Ordinal)
        if ($splitIndex -lt 0)
        {
            throw "Tail declaration split marker '$($snippet.SplitBefore)' was not found in $($snippet.Id)."
        }

        $declarationSource = $source.Substring($splitIndex).TrimEnd()
        $source = $source.Substring(0, $splitIndex).TrimEnd()
        [void]$builder.AppendLine("#line $($snippet.Line) `"$($snippet.SourcePath)`"")
        foreach ($line in ($declarationSource -split "`n"))
        {
            [void]$builder.AppendLine("    $line")
        }
        [void]$builder.AppendLine('#line default')
    }

    [void]$builder.AppendLine('    public static async Task<object?> RunAsync()')
    [void]$builder.AppendLine('    {')
    [void]$builder.AppendLine('        await Task.CompletedTask;')
    if (-not [string]::IsNullOrWhiteSpace($source))
    {
        [void]$builder.AppendLine("#line $($snippet.Line) `"$($snippet.SourcePath)`"")
        foreach ($line in ($source -split "`n"))
        {
            [void]$builder.AppendLine("        $line")
        }
        [void]$builder.AppendLine('#line default')
    }
    [void]$builder.AppendLine('        return null;')
    [void]$builder.AppendLine('    }')
    [void]$builder.AppendLine('}')
    [void]$builder.AppendLine('}')
    [void]$builder.AppendLine('#endif')
}

[void]$builder.AppendLine('#if !DOCUMENTATION_DIAGNOSTICS')
[void]$builder.AppendLine('namespace Kevlar.DocTests')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('internal static class SnippetCatalog')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    public static async Task RunAsync()')
[void]$builder.AppendLine('    {')
[void]$builder.AppendLine("        Console.WriteLine(`"Compiled $warningCleanSnippetCount warning-clean C# documentation snippets.`");")
[void]$builder.AppendLine('        var output = new StringWriter();')
[void]$builder.AppendLine('        var original = Console.Out;')
[void]$builder.AppendLine('        Console.SetOut(output);')
[void]$builder.AppendLine('        try')
[void]$builder.AppendLine('        {')

$observableSnippetIndex = -1
$timeoutExceededClauseSnippetIndex = -1
$systemTimeoutClauseTrapSnippetIndex = -1
$metricsSnippetIndex = -1
$retryNumbersSnippetIndex = -1
$gettingStartedRetryCountSnippetIndex = -1
$gettingStartedTimeoutOrderSnippetIndex = -1
$gettingStartedAmbientClauseSnippetIndex = -1
for ($snippetIndex = 0; $snippetIndex -lt $snippets.Count; $snippetIndex++)
{
    if ($snippets[$snippetIndex].RunName -eq 'pipeline-description')
    {
        $observableSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'timeout-exceeded-clause')
    {
        $timeoutExceededClauseSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'system-timeout-clause-trap')
    {
        $systemTimeoutClauseTrapSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'metrics-listener')
    {
        $metricsSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'retry-numbers')
    {
        $retryNumbersSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'getting-started-retry-count')
    {
        $gettingStartedRetryCountSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'getting-started-timeout-order')
    {
        $gettingStartedTimeoutOrderSnippetIndex = $snippetIndex
    }

    if ($snippets[$snippetIndex].RunName -eq 'getting-started-ambient-clause')
    {
        $gettingStartedAmbientClauseSnippetIndex = $snippetIndex
    }
}

if ($observableSnippetIndex -lt 0 `
    -or $timeoutExceededClauseSnippetIndex -lt 0 `
    -or $systemTimeoutClauseTrapSnippetIndex -lt 0 `
    -or $metricsSnippetIndex -lt 0 `
    -or $retryNumbersSnippetIndex -lt 0 `
    -or $gettingStartedRetryCountSnippetIndex -lt 0 `
    -or $gettingStartedTimeoutOrderSnippetIndex -lt 0 `
    -or $gettingStartedAmbientClauseSnippetIndex -lt 0)
{
    throw 'A required executable documentation snippet is missing.'
}

[void]$builder.AppendLine("            await Snippet$observableSnippetIndex.RunAsync();")
[void]$builder.AppendLine("            await Snippet$retryNumbersSnippetIndex.RunAsync();")
[void]$builder.AppendLine('        }')
[void]$builder.AppendLine('        finally')
[void]$builder.AppendLine('        {')
[void]$builder.AppendLine('            Console.SetOut(original);')
[void]$builder.AppendLine('        }')
[void]$builder.AppendLine('        var actual = output.ToString().Trim();')
[void]$builder.AppendLine('        var expected = "github: Timeout(30s) → Retry(3, exponential 250ms ×2, equal jitter, cap 30s) → CircuitBreaker(5 consecutive, break 30s) → ConcurrencyLimit(10, queue 5)" + Environment.NewLine + "0,1,2";')
[void]$builder.AppendLine('        if (!string.Equals(actual, expected, StringComparison.Ordinal))')
[void]$builder.AppendLine('        {')
[void]$builder.AppendLine('            throw new InvalidOperationException($"Documented executable output changed. Expected: {expected}; actual: {actual}");')
[void]$builder.AppendLine('        }')
for ($snippetIndex = 0; $snippetIndex -lt $snippets.Count; $snippetIndex++)
{
    $runName = $snippets[$snippetIndex].RunName
    if ($null -ne $runName -and $runName -ne 'pipeline-description')
    {
        [void]$builder.AppendLine("        await Snippet$snippetIndex.RunAsync();")
    }
}

[void]$builder.AppendLine('        Console.WriteLine("Executed documented pipeline behavior successfully.");')
[void]$builder.AppendLine('    }')
[void]$builder.AppendLine('}')
[void]$builder.AppendLine('}')
[void]$builder.AppendLine('#else')
[void]$builder.AppendLine('namespace Kevlar.DocTests')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('internal static class SnippetCatalog')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    public static Task RunAsync() => Task.CompletedTask;')
[void]$builder.AppendLine('}')
[void]$builder.AppendLine('}')
[void]$builder.AppendLine('#endif')

$generatedSource = $builder.ToString()
foreach ($forbiddenPattern in $forbiddenDocumentationPatterns.GetEnumerator())
{
    if ($generatedSource -match $forbiddenPattern.Value)
    {
        throw "Generated documentation source contains forbidden $($forbiddenPattern.Key)."
    }
}

[IO.File]::WriteAllText($generatedPath, $generatedSource)

[IO.File]::WriteAllText(
    $nugetConfigPath,
    @"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="local-packages" value="$([Security.SecurityElement]::Escape($resolvedPackagesPath))" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
"@)

$implicitUsings = if ($NoImplicitUsings) { 'disable' } else { 'enable' }
function Assert-ExpectedDocumentationDiagnostics
{
    param(
        [Parameter(Mandatory)]
        [string]$BuildOutput,

        [Parameter(Mandatory)]
        [string]$Framework
    )

    $expectedCounts = @{}
    foreach ($snippet in $snippets)
    {
        foreach ($expectedDiagnostic in $snippet.ExpectedDiagnostics)
        {
            $key = "$($snippet.Id)|$($expectedDiagnostic.Id)"
            $expectedCounts[$key] = [int]$expectedDiagnostic.Count
        }
    }

    $actualCounts = @{}
    $seenDiagnostics = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
    $diagnosticPattern = '(?m)^(?<path>.+?)\((?<line>[0-9]+),(?<column>[0-9]+)\): error (?<id>[A-Z]+[0-9]+):'
    foreach ($errorLine in [regex]::Matches($BuildOutput, '(?m)^(?<text>.*: error .*)$'))
    {
        if (-not [regex]::IsMatch($errorLine.Groups['text'].Value, $diagnosticPattern))
        {
            throw "Unexpected documentation diagnostic build failure: $($errorLine.Groups['text'].Value)"
        }
    }

    foreach ($match in [regex]::Matches($BuildOutput, $diagnosticPattern))
    {
        $diagnosticPath = [IO.Path]::GetFullPath($match.Groups['path'].Value)
        $diagnosticLine = [int]$match.Groups['line'].Value
        $diagnosticColumn = [int]$match.Groups['column'].Value
        $diagnosticId = $match.Groups['id'].Value
        $diagnosticKey = "$diagnosticPath|$diagnosticLine|$diagnosticColumn|$diagnosticId"
        if (-not $seenDiagnostics.Add($diagnosticKey))
        {
            continue
        }

        $matchingSnippet = $snippets |
            Where-Object {
                [IO.Path]::GetFullPath($_.SourcePath) -eq $diagnosticPath `
                    -and $diagnosticLine -ge $_.Line `
                    -and $diagnosticLine -le $_.EndLine
            } |
            Select-Object -First 1
        if ($null -eq $matchingSnippet)
        {
            throw "Unexpected $diagnosticId at ${diagnosticPath}:$diagnosticLine while building documentation for $Framework."
        }

        $expectedDiagnostic = $matchingSnippet.ExpectedDiagnostics |
            Where-Object Id -eq $diagnosticId |
            Select-Object -First 1
        if ($null -eq $expectedDiagnostic)
        {
            throw "Unexpected $diagnosticId in $($matchingSnippet.Id) while building documentation for $Framework."
        }

        $key = "$($matchingSnippet.Id)|$diagnosticId"
        $actualCounts[$key] = 1 + [int]$actualCounts[$key]
    }

    foreach ($expected in $expectedCounts.GetEnumerator())
    {
        $actualCount = [int]$actualCounts[$expected.Key]
        if ($actualCount -ne $expected.Value)
        {
            throw "Expected $($expected.Value) diagnostic(s) for $($expected.Key) on $Framework; found $actualCount."
        }
    }
}

& dotnet restore $projectPath --configfile $nugetConfigPath `
    "-p:KevlarPackageVersion=$Version" `
    "-p:GeneratedSnippetsPath=$generatedPath" `
    "-p:ImplicitUsings=$implicitUsings"

if ($LASTEXITCODE -ne 0)
{
    throw "Documentation snippet restore failed with exit code $LASTEXITCODE."
}

foreach ($framework in @('net8.0', 'net10.0'))
{
    $buildArguments = @(
        'build'
        $projectPath
        '-c', 'Release'
        '--framework', $framework
        '--no-restore'
        '--no-incremental'
        "-p:KevlarPackageVersion=$Version"
        "-p:GeneratedSnippetsPath=$generatedPath"
        "-p:ImplicitUsings=$implicitUsings"
    )
    $buildOutput = (& dotnet @buildArguments 2>&1 | Out-String)
    $buildExitCode = $LASTEXITCODE
    Write-Host ($buildOutput.TrimEnd())
    if ($buildExitCode -ne 0)
    {
        throw "Documentation snippet project failed to build for $framework with exit code $buildExitCode."
    }

    & dotnet run --project $projectPath -c Release --framework $framework --no-build --no-restore `
        "-p:KevlarPackageVersion=$Version" `
        "-p:GeneratedSnippetsPath=$generatedPath" `
        "-p:ImplicitUsings=$implicitUsings"

    if ($LASTEXITCODE -ne 0)
    {
        throw "Documentation snippet project failed for $framework with exit code $LASTEXITCODE."
    }

    if ($diagnosticSnippetCount -gt 0)
    {
        $diagnosticArguments = $buildArguments + '-p:DefineConstants=DOCUMENTATION_DIAGNOSTICS'
        $diagnosticOutput = (& dotnet @diagnosticArguments 2>&1 | Out-String)
        $diagnosticExitCode = $LASTEXITCODE
        if ($diagnosticExitCode -eq 0)
        {
            throw "Documentation diagnostic examples unexpectedly built without errors for $framework."
        }

        try
        {
            Assert-ExpectedDocumentationDiagnostics -BuildOutput $diagnosticOutput -Framework $framework
        }
        catch
        {
            Write-Host ($diagnosticOutput.TrimEnd())
            throw
        }

        Write-Host "Validated $diagnosticSnippetCount diagnostic C# examples with $expectedDiagnosticCount exact errors on $framework."
    }
}

exit 0
