<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup Condition="'$(UsePackedPackages)' != 'true'">
    <ProjectReference Include="..\..\src\Kevlar\Kevlar.csproj" />
    <ProjectReference Include="..\..\src\Kevlar.Extensions.DependencyInjection\Kevlar.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Kevlar.Extensions.Http\Kevlar.Extensions.Http.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UsePackedPackages)' == 'true'">
    <PackageReference Include="Kevlar" VersionOverride="$(KevlarSamplePackageVersion)" />
    <PackageReference Include="Kevlar.Extensions.DependencyInjection" VersionOverride="$(KevlarSamplePackageVersion)" />
    <PackageReference Include="Kevlar.Extensions.Http" VersionOverride="$(KevlarSamplePackageVersion)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
</Project>
